chore: updated package manager to bun

diff --git a/.husky/pre-commit b/.husky/pre-commit
--- a/.husky/pre-commit
+++ b/.husky/pre-commit
@@ -1,8 +1,8 @@
 #!/usr/bin/env sh
 
-command -v pnpm >/dev/null 2>&1 || {
-  echo "husky (pre-commit): pnpm not found, please install pnpm to run lint-staged." >&2
+command -v bun >/dev/null 2>&1 || {
+  echo "husky (pre-commit): bun not found, please install Bun to run lint-staged." >&2
   exit 1
 }
 
-pnpm exec lint-staged
+bunx --bun lint-staged
